[0m09:31:55.031864 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067d4ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067b8450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106832c10>]}


============================== 09:31:55.033949 | 4e19d8de-faf9-4c72-a1db-cd203e61195b ==============================
[0m09:31:55.033949 [info ] [MainThread]: Running with dbt=1.10.11
[0m09:31:55.034200 [debug] [MainThread]: running dbt with arguments {'version_check': 'True', 'introspect': 'True', 'fail_fast': 'False', 'log_format': 'default', 'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'profiles_dir': '/Users/mansstormer/.dbt', 'send_anonymous_usage_stats': 'True', 'no_print': 'None', 'invocation_command': 'dbt init lundahoj', 'use_experimental_parser': 'False', 'target_path': 'None', 'write_json': 'True', 'use_colors': 'True', 'debug': 'False', 'static_parser': 'True', 'quiet': 'False', 'log_path': 'logs', 'cache_selected_only': 'False', 'printer_width': '80', 'warn_error': 'None', 'indirect_selection': 'eager', 'empty': 'None', 'log_cache_events': 'False'}
[0m09:31:55.043546 [debug] [MainThread]: Starter project path: /opt/miniconda3/envs/biker/lib/python3.11/site-packages/dbt/include/starter_project
[0m09:31:55.046371 [info ] [MainThread]: 
Your new dbt project "lundahoj" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:31:55.046526 [info ] [MainThread]: Setting up your profile.
[0m09:35:24.342439 [info ] [MainThread]: Profile lundahoj written to /Users/mansstormer/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m09:35:24.362723 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 209.35854, "process_in_blocks": "0", "process_kernel_time": 0.156028, "process_mem_max_rss": "132792320", "process_out_blocks": "0", "process_user_time": 0.85334}
[0m09:35:24.363566 [debug] [MainThread]: Command `dbt init` succeeded at 09:35:24.363432 after 209.36 seconds
[0m09:35:24.364027 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106857610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x101298e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1012991d0>]}
[0m09:35:24.364444 [debug] [MainThread]: Flushing usage events
[0m09:35:25.843774 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:36:49.896518 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f24390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f8a190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106fa6c50>]}


============================== 09:36:49.898705 | 609083cc-f644-444b-91b8-fffba50599ad ==============================
[0m09:36:49.898705 [info ] [MainThread]: Running with dbt=1.10.11
[0m09:36:49.898940 [debug] [MainThread]: running dbt with arguments {'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'warn_error': 'None', 'fail_fast': 'False', 'log_format': 'default', 'cache_selected_only': 'False', 'send_anonymous_usage_stats': 'True', 'invocation_command': 'dbt debug', 'debug': 'False', 'target_path': 'None', 'static_parser': 'True', 'partial_parse': 'True', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_cache_events': 'False', 'use_experimental_parser': 'False', 'version_check': 'True', 'printer_width': '80', 'profiles_dir': '/Users/mansstormer/.dbt', 'introspect': 'True', 'write_json': 'True', 'log_path': 'logs', 'use_colors': 'True', 'indirect_selection': 'eager'}
[0m09:36:49.906251 [info ] [MainThread]: dbt version: 1.10.11
[0m09:36:49.906427 [info ] [MainThread]: python version: 3.11.9
[0m09:36:49.906559 [info ] [MainThread]: python path: /opt/miniconda3/envs/biker/bin/python3.11
[0m09:36:49.906665 [info ] [MainThread]: os info: macOS-15.6.1-arm64-arm-64bit
[0m09:36:49.936984 [info ] [MainThread]: Using profiles dir at /Users/mansstormer/.dbt
[0m09:36:49.937188 [info ] [MainThread]: Using profiles.yml file at /Users/mansstormer/.dbt/profiles.yml
[0m09:36:49.937299 [info ] [MainThread]: Using dbt_project.yml file at /Users/mansstormer/Documents/Projects/Lundahoj Analytics Neon/dbt_project.yml
[0m09:36:49.937428 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m09:36:49.939239 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.069048375, "process_in_blocks": "0", "process_kernel_time": 0.10315, "process_mem_max_rss": "132120576", "process_out_blocks": "0", "process_user_time": 0.820036}
[0m09:36:49.939404 [debug] [MainThread]: Command `dbt debug` failed at 09:36:49.939374 after 0.07 seconds
[0m09:36:49.939528 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100a6cd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100a6d010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f23a90>]}
[0m09:36:49.939653 [debug] [MainThread]: Flushing usage events
[0m09:36:50.456366 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:44:59.045961 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072e9650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109e01ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109dff510>]}


============================== 09:44:59.048125 | b3db8003-7618-4791-a63b-3a3d9b75e1c0 ==============================
[0m09:44:59.048125 [info ] [MainThread]: Running with dbt=1.10.11
[0m09:44:59.048368 [debug] [MainThread]: running dbt with arguments {'target_path': 'None', 'static_parser': 'True', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'printer_width': '80', 'fail_fast': 'False', 'indirect_selection': 'eager', 'introspect': 'True', 'invocation_command': 'dbt debug', 'log_path': 'logs', 'partial_parse': 'True', 'no_print': 'None', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'empty': 'None', 'quiet': 'False', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mansstormer/.dbt', 'write_json': 'True', 'log_format': 'default', 'log_cache_events': 'False', 'use_experimental_parser': 'False'}
[0m09:44:59.055561 [info ] [MainThread]: dbt version: 1.10.11
[0m09:44:59.055734 [info ] [MainThread]: python version: 3.11.9
[0m09:44:59.055858 [info ] [MainThread]: python path: /opt/miniconda3/envs/biker/bin/python3.11
[0m09:44:59.055960 [info ] [MainThread]: os info: macOS-15.6.1-arm64-arm-64bit
[0m09:44:59.085738 [info ] [MainThread]: Using profiles dir at /Users/mansstormer/.dbt
[0m09:44:59.085945 [info ] [MainThread]: Using profiles.yml file at /Users/mansstormer/.dbt/profiles.yml
[0m09:44:59.086058 [info ] [MainThread]: Using dbt_project.yml file at /Users/mansstormer/Documents/Projects/Lundahoj Analytics Neon/dbt_project.yml
[0m09:44:59.086409 [info ] [MainThread]: adapter type: postgres
[0m09:44:59.086512 [info ] [MainThread]: adapter version: 1.9.1
[0m09:44:59.086615 [info ] [MainThread]: Configuration:
[0m09:44:59.086710 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m09:44:59.086796 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m09:44:59.086882 [info ] [MainThread]: Required dependencies:
[0m09:44:59.086994 [debug] [MainThread]: Executing "git --help"
[0m09:44:59.098475 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m09:44:59.098849 [debug] [MainThread]: STDERR: "b''"
[0m09:44:59.099000 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m09:44:59.099127 [info ] [MainThread]: Connection:
[0m09:44:59.099259 [info ] [MainThread]:   host: ep-aged-bonus-ag3j3swz.c-2.eu-central-1.aws.neon.tech
[0m09:44:59.099355 [info ] [MainThread]:   port: 5432
[0m09:44:59.099443 [info ] [MainThread]:   user: neondb_owner
[0m09:44:59.099530 [info ] [MainThread]:   database: neondb
[0m09:44:59.099614 [info ] [MainThread]:   schema: analytics
[0m09:44:59.099699 [info ] [MainThread]:   connect_timeout: 10
[0m09:44:59.099784 [info ] [MainThread]:   role: None
[0m09:44:59.099869 [info ] [MainThread]:   search_path: None
[0m09:44:59.099954 [info ] [MainThread]:   keepalives_idle: 0
[0m09:44:59.100036 [info ] [MainThread]:   sslmode: None
[0m09:44:59.100119 [info ] [MainThread]:   sslcert: None
[0m09:44:59.100203 [info ] [MainThread]:   sslkey: None
[0m09:44:59.100286 [info ] [MainThread]:   sslrootcert: None
[0m09:44:59.100371 [info ] [MainThread]:   application_name: dbt
[0m09:44:59.100455 [info ] [MainThread]:   retries: 1
[0m09:44:59.100693 [info ] [MainThread]: Registered adapter: postgres=1.9.1
[0m09:44:59.150416 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m09:44:59.208401 [debug] [MainThread]: Using postgres connection "debug"
[0m09:44:59.208571 [debug] [MainThread]: On debug: select 1 as id
[0m09:44:59.208669 [debug] [MainThread]: Opening a new connection, currently in state init
[0m09:44:59.392447 [debug] [MainThread]: SQL status: SELECT 1 in 0.184 seconds
[0m09:44:59.393267 [debug] [MainThread]: On debug: Close
[0m09:44:59.393650 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m09:44:59.393904 [info ] [MainThread]: [31m1 check failed:[0m
[0m09:44:59.394128 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/mansstormer/Documents/Projects/Lundahoj Analytics Neon/dbt_project.yml> not found

[0m09:44:59.397759 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.37775964, "process_in_blocks": "0", "process_kernel_time": 0.15543, "process_mem_max_rss": "143933440", "process_out_blocks": "0", "process_user_time": 0.8519}
[0m09:44:59.398118 [debug] [MainThread]: Command `dbt debug` failed at 09:44:59.398045 after 0.38 seconds
[0m09:44:59.398355 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m09:44:59.398602 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1047d8d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1047d90d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10acb1350>]}
[0m09:44:59.398880 [debug] [MainThread]: Flushing usage events
[0m09:44:59.847865 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:49:54.238295 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x121d937d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x121db7010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x121db76d0>]}


============================== 10:49:54.240542 | e6f259e8-07f3-4ad8-aa00-783811833c8f ==============================
[0m10:49:54.240542 [info ] [MainThread]: Running with dbt=1.10.11
[0m10:49:54.240790 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'fail_fast': 'False', 'quiet': 'False', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error': 'None', 'write_json': 'True', 'profiles_dir': '/Users/mansstormer/.dbt', 'log_format': 'default', 'empty': 'False', 'log_cache_events': 'False', 'invocation_command': 'dbt build', 'indirect_selection': 'eager', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'partial_parse': 'True', 'no_print': 'None', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m10:49:54.241030 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mansstormer/Documents/Projects/Lundahoj Analytics Neon/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:49:54.247669 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.03736496, "process_in_blocks": "0", "process_kernel_time": 0.139959, "process_mem_max_rss": "129433600", "process_out_blocks": "0", "process_user_time": 0.822619}
[0m10:49:54.247875 [debug] [MainThread]: Command `dbt build` failed at 10:49:54.247834 after 0.04 seconds
[0m10:49:54.248042 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x101550d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x121d966d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x121dcbf90>]}
[0m10:49:54.248211 [debug] [MainThread]: Flushing usage events
[0m10:49:54.778905 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:51:19.814335 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10568a110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1081cf150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1081cf810>]}


============================== 10:51:19.815766 | 815203fd-a859-452f-97e4-51d4987a5912 ==============================
[0m10:51:19.815766 [info ] [MainThread]: Running with dbt=1.10.11
[0m10:51:19.816008 [debug] [MainThread]: running dbt with arguments {'target_path': 'None', 'quiet': 'False', 'use_colors': 'True', 'static_parser': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'write_json': 'True', 'use_experimental_parser': 'False', 'profiles_dir': '/Users/mansstormer/.dbt', 'fail_fast': 'False', 'log_cache_events': 'False', 'printer_width': '80', 'log_format': 'default', 'introspect': 'True', 'empty': 'False', 'debug': 'False', 'log_path': 'logs', 'send_anonymous_usage_stats': 'True', 'no_print': 'None', 'version_check': 'True', 'indirect_selection': 'eager', 'partial_parse': 'True', 'invocation_command': 'dbt build', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m10:51:19.816222 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mansstormer/Documents/Projects/Lundahoj Analytics Neon/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:51:19.817126 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.025681833, "process_in_blocks": "0", "process_kernel_time": 0.080126, "process_mem_max_rss": "127762432", "process_out_blocks": "0", "process_user_time": 0.803764}
[0m10:51:19.817293 [debug] [MainThread]: Command `dbt build` failed at 10:51:19.817260 after 0.03 seconds
[0m10:51:19.817427 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1081dff50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1081dff90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107493c90>]}
[0m10:51:19.817553 [debug] [MainThread]: Flushing usage events
[0m10:51:20.282865 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:46:54.143203 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10aa53b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10aa53c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10aa73d90>]}


============================== 08:46:54.145369 | 5ad902d7-8779-45ea-82c3-da67d8087b87 ==============================
[0m08:46:54.145369 [info ] [MainThread]: Running with dbt=1.10.11
[0m08:46:54.145628 [debug] [MainThread]: running dbt with arguments {'cache_selected_only': 'False', 'empty': 'False', 'profiles_dir': '/Users/mansstormer/.dbt', 'invocation_command': 'dbt build', 'log_cache_events': 'False', 'introspect': 'True', 'static_parser': 'True', 'warn_error': 'None', 'target_path': 'None', 'printer_width': '80', 'use_colors': 'True', 'debug': 'False', 'partial_parse': 'True', 'use_experimental_parser': 'False', 'indirect_selection': 'eager', 'send_anonymous_usage_stats': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'write_json': 'True', 'log_format': 'default', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m08:46:54.145884 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mansstormer/Documents/Projects/Lundahoj Analytics Neon/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:46:54.147517 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.028662626, "process_in_blocks": "0", "process_kernel_time": 0.101481, "process_mem_max_rss": "127811584", "process_out_blocks": "0", "process_user_time": 0.792984}
[0m08:46:54.147694 [debug] [MainThread]: Command `dbt build` failed at 08:46:54.147658 after 0.03 seconds
[0m08:46:54.147832 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10aa559d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105414d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105415010>]}
[0m08:46:54.147959 [debug] [MainThread]: Flushing usage events
[0m08:46:54.595909 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:57:13.243614 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107e4a410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11b1b31d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11b1b3890>]}


============================== 15:57:13.245785 | fd334e7a-d3db-45a7-b060-f2394e84acca ==============================
[0m15:57:13.245785 [info ] [MainThread]: Running with dbt=1.10.11
[0m15:57:13.246045 [debug] [MainThread]: running dbt with arguments {'warn_error': 'None', 'use_experimental_parser': 'False', 'partial_parse': 'True', 'printer_width': '80', 'log_format': 'default', 'fail_fast': 'False', 'static_parser': 'True', 'version_check': 'True', 'debug': 'False', 'profiles_dir': '/Users/mansstormer/.dbt', 'introspect': 'True', 'use_colors': 'True', 'send_anonymous_usage_stats': 'True', 'log_path': 'logs', 'empty': 'False', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'no_print': 'None', 'target_path': 'None', 'invocation_command': 'dbt build', 'log_cache_events': 'False', 'cache_selected_only': 'False', 'indirect_selection': 'eager', 'write_json': 'True'}
[0m15:57:13.246291 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mansstormer/Documents/Projects/Lundahoj Analytics Neon/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:57:13.247984 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.029766668, "process_in_blocks": "0", "process_kernel_time": 0.107114, "process_mem_max_rss": "127778816", "process_out_blocks": "0", "process_user_time": 0.790327}
[0m15:57:13.248175 [debug] [MainThread]: Command `dbt build` failed at 15:57:13.248136 after 0.03 seconds
[0m15:57:13.248315 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11b127b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11b127950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11b127a10>]}
[0m15:57:13.248449 [debug] [MainThread]: Flushing usage events
[0m15:57:13.697075 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:05:18.263953 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108657bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086dee10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086df4d0>]}


============================== 10:05:18.265901 | 3302b60a-e436-4200-81b3-c7c53dc4c5a7 ==============================
[0m10:05:18.265901 [info ] [MainThread]: Running with dbt=1.10.11
[0m10:05:18.266125 [debug] [MainThread]: running dbt with arguments {'write_json': 'True', 'target_path': 'None', 'use_colors': 'True', 'no_print': 'None', 'introspect': 'True', 'use_experimental_parser': 'False', 'invocation_command': 'dbt build --select mart_station_hourly_occupancy', 'version_check': 'True', 'cache_selected_only': 'False', 'quiet': 'False', 'partial_parse': 'True', 'log_cache_events': 'False', 'empty': 'False', 'printer_width': '80', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'warn_error': 'None', 'profiles_dir': '/Users/mansstormer/.dbt', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'log_format': 'default'}
[0m10:05:18.266368 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mansstormer/Documents/Projects/lundahoj-analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:05:18.267544 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.02770275, "process_in_blocks": "0", "process_kernel_time": 0.098495, "process_mem_max_rss": "128352256", "process_out_blocks": "0", "process_user_time": 0.78708}
[0m10:05:18.267751 [debug] [MainThread]: Command `dbt build` failed at 10:05:18.267714 after 0.03 seconds
[0m10:05:18.267891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105998fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103090d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108318110>]}
[0m10:05:18.268021 [debug] [MainThread]: Flushing usage events
[0m10:05:18.731870 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:47:33.896110 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fab6d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108037c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d51210>]}


============================== 19:47:33.898293 | afb3222f-1f5d-459b-85a5-c4ecd8a710e8 ==============================
[0m19:47:33.898293 [info ] [MainThread]: Running with dbt=1.10.11
[0m19:47:33.898523 [debug] [MainThread]: running dbt with arguments {'cache_selected_only': 'False', 'use_experimental_parser': 'False', 'fail_fast': 'False', 'no_print': 'None', 'empty': 'False', 'quiet': 'False', 'warn_error': 'None', 'write_json': 'True', 'target_path': 'None', 'printer_width': '80', 'static_parser': 'True', 'introspect': 'True', 'version_check': 'True', 'debug': 'False', 'profiles_dir': '/Users/mansstormer/.dbt', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'use_colors': 'True', 'send_anonymous_usage_stats': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'partial_parse': 'True', 'invocation_command': 'dbt build', 'log_path': 'logs', 'log_format': 'default'}
[0m19:47:33.898758 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mansstormer/Documents/Projects/lundahoj-analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:47:33.900393 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.03172729, "process_in_blocks": "0", "process_kernel_time": 0.112247, "process_mem_max_rss": "128040960", "process_out_blocks": "0", "process_user_time": 0.804464}
[0m19:47:33.900577 [debug] [MainThread]: Command `dbt build` failed at 19:47:33.900544 after 0.03 seconds
[0m19:47:33.900719 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d7b1d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d7b310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d52690>]}
[0m19:47:33.900849 [debug] [MainThread]: Flushing usage events
[0m19:47:34.440535 [debug] [MainThread]: An error was encountered while trying to flush usage events
